kind: Service
apiVersion: v1
metadata:
    name: book-service
spec:
    type: NodePort
    selector:
        app: book-app
    ports:
    - name: book-service
      protocol: TCP
      port: 80
      targetPort: 8080
